
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('af', 'Afrikaans', 'Afrikaans');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('sq', 'Albanian', 'shqiptare');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('ar', 'Arabic', 'عربي');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('hy', 'Armenian', 'հայերեն');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('eu', 'Basque', 'euskara');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('be', 'Belarusian', 'беларускі');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('bn', 'Bengali', 'বাংলা');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('bs', 'Bosnian', 'bosanski');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('ca', 'Catalan', 'català');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('zh-cn', 'Simplified Chinese', '简体中文');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('zh-tw', 'Traditional Chinese', '繁體中文');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('cs', 'Czech', 'čeština');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('da', 'Danish', 'dansk');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('nl', 'Dutch', 'Nederlandse taal');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('en', 'English', 'English');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('eo', 'Esperanto', 'Esperanto');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('et', 'Estonian', 'eesti keel');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('fi', 'Finnish', 'Suomen kieli');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('fil, tl', 'Filipino', 'Filipino');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('fr', 'French', 'Français');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('ka', 'Georgian', 'ქართული');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('de', 'German', 'Deutsch');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('gl', 'Galician', 'galego');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('el', 'Greek', 'Ελληνικά');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('he', 'Hebrew', 'עִברִית');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('hi', 'Hindi', 'हिन्दी');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('hr', 'Croatian', 'hrvatski');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('hu', 'Hungarian', 'magyar');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('is', 'Icelandic', 'íslenskur');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('id', 'Indonesian', 'bahasa Indonesia');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('it', 'Italian', 'Italiano');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('ja', 'Japanese', '日本語');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('kk', 'Kazakh', 'қазақ');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('km', 'Khmer', 'ភាសាខ្មែរ');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('ko', 'Korean', '한국어');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('lv', 'Latvian', 'latviešu');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('lt', 'Lithuanian', 'lietuvių kalba');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('lb', 'Luxembourgish', 'Lëtzebuergesch');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('mk', 'Macedonian', 'македонски');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('ml', 'Malayalam', 'മലയാളം ഭാഷ');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('ms', 'Malay', 'bahasa melayu');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('mn', 'Mongolian', 'Монгол хэл');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('no', 'Norwegian', 'norsk');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('fa', 'Persian', 'فارسی');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('pl', 'Polish', 'polski');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('pt-pt', 'Portuguese', 'Português');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('ru', 'Russian', 'Русский');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('sr', 'Serbian', 'српски');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('es', 'Spanish', 'Española');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('sw', 'Swahili', 'kiswahili');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('sv', 'Swedish', 'svensk');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('sl', 'Slovenian', 'Slovenščina');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('sk', 'Slovak', 'slovenčina');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('ta', 'Tamil', 'தமிழ்');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('te', 'Telugu', 'తెలుగు');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('th', 'Thai', 'ไทย');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('tr', 'Turkish', 'Türkçe');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('uk', 'Ukrainian', 'Українська мова');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('ur', 'Urdu', 'اردو زبان');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('uz', 'Uzbek', 'ozbek tili');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('vi', 'Vietnamese', 'Tiếng Việt');
INSERT INTO `languages` (`LanguageCode`, `EnglishName`, `Name`) VALUES ('ro', 'Romanian', 'română');



