// <auto-generated />
using System;
using Captioneer.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Captioneer.API.Migrations
{
    [DbContext(typeof(CaptioneerDBContext))]
    [Migration("20221116154735_ChangeYearLength")]
    partial class ChangeYearLength
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Captioneer.API.Entities.Actor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("ID");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("Captioneer.API.Entities.ActorMovie", b =>
                {
                    b.Property<int>("ActorID")
                        .HasColumnType("int");

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.HasKey("ActorID", "MovieID");

                    b.HasIndex("MovieID");

                    b.ToTable("ActorMovies");
                });

            modelBuilder.Entity("Captioneer.API.Entities.ActorTVShow", b =>
                {
                    b.Property<int>("ActorID")
                        .HasColumnType("int");

                    b.Property<int>("TVShowID")
                        .HasColumnType("int");

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.HasKey("ActorID", "TVShowID");

                    b.HasIndex("MovieID");

                    b.ToTable("ActorTVShows");
                });

            modelBuilder.Entity("Captioneer.API.Entities.Admin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Captioneer.API.Entities.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AdminID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SubtitleMovieID")
                        .HasColumnType("int");

                    b.Property<int>("SubtitleTVShowID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AdminID");

                    b.HasIndex("SubtitleMovieID");

                    b.HasIndex("SubtitleTVShowID");

                    b.HasIndex("UserID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Captioneer.API.Entities.Creator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("ID");

                    b.ToTable("Creators");
                });

            modelBuilder.Entity("Captioneer.API.Entities.CreatorMovie", b =>
                {
                    b.Property<int>("CreatorID")
                        .HasColumnType("int");

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("CreatorID", "MovieID", "Position");

                    b.HasIndex("MovieID");

                    b.ToTable("CreatorsMovie");
                });

            modelBuilder.Entity("Captioneer.API.Entities.CreatorTVShow", b =>
                {
                    b.Property<int>("CreatorID")
                        .HasColumnType("int");

                    b.Property<int>("TVShowID")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("CreatorID", "TVShowID", "Position");

                    b.HasIndex("TVShowID");

                    b.ToTable("CreatorsTVShows");
                });

            modelBuilder.Entity("Captioneer.API.Entities.DirectMessage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RecipientUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RecipientUserID");

                    b.HasIndex("UserID");

                    b.ToTable("DirectMessages");
                });

            modelBuilder.Entity("Captioneer.API.Entities.Episode", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<double>("RatingValue")
                        .HasColumnType("double");

                    b.Property<int>("Runtime")
                        .HasColumnType("int");

                    b.Property<int>("SeasonID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SeasonID");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Captioneer.API.Entities.Genre", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ID");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Captioneer.API.Entities.GenreMovie", b =>
                {
                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.HasKey("GenreID", "MovieID");

                    b.HasIndex("MovieID");

                    b.ToTable("GenresMovie");
                });

            modelBuilder.Entity("Captioneer.API.Entities.GenreTVShow", b =>
                {
                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.Property<int>("TVShowID")
                        .HasColumnType("int");

                    b.HasKey("GenreID", "TVShowID");

                    b.HasIndex("TVShowID");

                    b.ToTable("GenresTVShows");
                });

            modelBuilder.Entity("Captioneer.API.Entities.Language", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Flag")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Captioneer.API.Entities.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CoverArt")
                        .HasColumnType("longtext");

                    b.Property<string>("IMDBId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IMDBRatingCount")
                        .HasColumnType("int");

                    b.Property<double>("IMDBRatingValue")
                        .HasColumnType("double");

                    b.Property<string>("MetacriticValue")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("RottenTomatoesValue")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<int>("Runtime")
                        .HasColumnType("int");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Captioneer.API.Entities.Season", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CoverArt")
                        .HasColumnType("longtext");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("int");

                    b.Property<int>("TVShowID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TVShowID");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Captioneer.API.Entities.ShootingPlace", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MapsCoordinates")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("ShootingPlaces");
                });

            modelBuilder.Entity("Captioneer.API.Entities.ShootingPlaceMovie", b =>
                {
                    b.Property<int>("ShootingPlaceID")
                        .HasColumnType("int");

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.HasKey("ShootingPlaceID", "MovieID");

                    b.HasIndex("MovieID");

                    b.ToTable("ShootingPlacesMovie");
                });

            modelBuilder.Entity("Captioneer.API.Entities.ShootingPlaceTVShow", b =>
                {
                    b.Property<int>("ShootingPlaceID")
                        .HasColumnType("int");

                    b.Property<int>("TVShowID")
                        .HasColumnType("int");

                    b.HasKey("ShootingPlaceID", "TVShowID");

                    b.HasIndex("TVShowID");

                    b.ToTable("ShootingPlacesTVShows");
                });

            modelBuilder.Entity("Captioneer.API.Entities.SubtitleMovie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AdminID")
                        .HasColumnType("int");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<int>("LanguageID")
                        .HasColumnType("int");

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<double>("RatingValue")
                        .HasColumnType("double");

                    b.Property<string>("SubtitlePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("AdminID");

                    b.HasIndex("LanguageID");

                    b.HasIndex("MovieID");

                    b.ToTable("SubtitleMovies");
                });

            modelBuilder.Entity("Captioneer.API.Entities.SubtitleTVShow", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AdminID")
                        .HasColumnType("int");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<int>("EpisodeID")
                        .HasColumnType("int");

                    b.Property<int>("LanguageID")
                        .HasColumnType("int");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<double>("RatingValue")
                        .HasColumnType("double");

                    b.Property<string>("SubtitlePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("AdminID");

                    b.HasIndex("EpisodeID");

                    b.HasIndex("LanguageID");

                    b.ToTable("SubtitleTVShows");
                });

            modelBuilder.Entity("Captioneer.API.Entities.SubtitleUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<double>("RatingValue")
                        .HasColumnType("double");

                    b.Property<int?>("SubtitleMovieID")
                        .HasColumnType("int");

                    b.Property<int?>("SubtitleTVShowID")
                        .HasColumnType("int");

                    b.Property<int?>("TranslationID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SubtitleMovieID");

                    b.HasIndex("SubtitleTVShowID");

                    b.HasIndex("TranslationID");

                    b.HasIndex("UserID");

                    b.ToTable("SubtitleUsers");
                });

            modelBuilder.Entity("Captioneer.API.Entities.Translation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LanguageID")
                        .HasColumnType("int");

                    b.Property<string>("SubtitlePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("LanguageID");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("Captioneer.API.Entities.TVShow", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CoverArt")
                        .HasColumnType("longtext");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("int");

                    b.Property<string>("IMDBId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IMDBRatingCount")
                        .HasColumnType("int");

                    b.Property<double>("IMDBRatingValue")
                        .HasColumnType("double");

                    b.Property<string>("MetacriticValue")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("RottenTomatoesValue")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<int>("SeasonCount")
                        .HasColumnType("int");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID");

                    b.ToTable("TVShows");
                });

            modelBuilder.Entity("Captioneer.API.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AdminID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID");

                    b.HasIndex("AdminID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Captioneer.API.Entities.ActorMovie", b =>
                {
                    b.HasOne("Captioneer.API.Entities.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Captioneer.API.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Captioneer.API.Entities.ActorTVShow", b =>
                {
                    b.HasOne("Captioneer.API.Entities.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Captioneer.API.Entities.TVShow", "TVShow")
                        .WithMany()
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("TVShow");
                });

            modelBuilder.Entity("Captioneer.API.Entities.Admin", b =>
                {
                    b.HasOne("Captioneer.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Captioneer.API.Entities.Comment", b =>
                {
                    b.HasOne("Captioneer.API.Entities.Admin", null)
                        .WithMany("RemovedComments")
                        .HasForeignKey("AdminID");

                    b.HasOne("Captioneer.API.Entities.SubtitleMovie", "SubtitleMovie")
                        .WithMany()
                        .HasForeignKey("SubtitleMovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Captioneer.API.Entities.SubtitleTVShow", "SubtitleTVShow")
                        .WithMany()
                        .HasForeignKey("SubtitleTVShowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Captioneer.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubtitleMovie");

                    b.Navigation("SubtitleTVShow");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Captioneer.API.Entities.CreatorMovie", b =>
                {
                    b.HasOne("Captioneer.API.Entities.Creator", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Captioneer.API.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Captioneer.API.Entities.CreatorTVShow", b =>
                {
                    b.HasOne("Captioneer.API.Entities.Creator", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Captioneer.API.Entities.TVShow", "TVShow")
                        .WithMany()
                        .HasForeignKey("TVShowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("TVShow");
                });

            modelBuilder.Entity("Captioneer.API.Entities.DirectMessage", b =>
                {
                    b.HasOne("Captioneer.API.Entities.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Captioneer.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipientUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Captioneer.API.Entities.Episode", b =>
                {
                    b.HasOne("Captioneer.API.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Captioneer.API.Entities.GenreMovie", b =>
                {
                    b.HasOne("Captioneer.API.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Captioneer.API.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Captioneer.API.Entities.GenreTVShow", b =>
                {
                    b.HasOne("Captioneer.API.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Captioneer.API.Entities.TVShow", "TVShow")
                        .WithMany()
                        .HasForeignKey("TVShowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("TVShow");
                });

            modelBuilder.Entity("Captioneer.API.Entities.Season", b =>
                {
                    b.HasOne("Captioneer.API.Entities.TVShow", "TVShow")
                        .WithMany()
                        .HasForeignKey("TVShowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TVShow");
                });

            modelBuilder.Entity("Captioneer.API.Entities.ShootingPlaceMovie", b =>
                {
                    b.HasOne("Captioneer.API.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Captioneer.API.Entities.ShootingPlace", "ShootingPlace")
                        .WithMany()
                        .HasForeignKey("ShootingPlaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("ShootingPlace");
                });

            modelBuilder.Entity("Captioneer.API.Entities.ShootingPlaceTVShow", b =>
                {
                    b.HasOne("Captioneer.API.Entities.ShootingPlace", "ShootingPlace")
                        .WithMany()
                        .HasForeignKey("ShootingPlaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Captioneer.API.Entities.TVShow", "TVShow")
                        .WithMany()
                        .HasForeignKey("TVShowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShootingPlace");

                    b.Navigation("TVShow");
                });

            modelBuilder.Entity("Captioneer.API.Entities.SubtitleMovie", b =>
                {
                    b.HasOne("Captioneer.API.Entities.Admin", null)
                        .WithMany("RemovedMovieSubtitles")
                        .HasForeignKey("AdminID");

                    b.HasOne("Captioneer.API.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Captioneer.API.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Captioneer.API.Entities.SubtitleTVShow", b =>
                {
                    b.HasOne("Captioneer.API.Entities.Admin", null)
                        .WithMany("RemovedTVShowSubtitles")
                        .HasForeignKey("AdminID");

                    b.HasOne("Captioneer.API.Entities.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Captioneer.API.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Captioneer.API.Entities.SubtitleUser", b =>
                {
                    b.HasOne("Captioneer.API.Entities.SubtitleMovie", "SubtitleMovie")
                        .WithMany()
                        .HasForeignKey("SubtitleMovieID");

                    b.HasOne("Captioneer.API.Entities.SubtitleTVShow", "SubtitleTVShow")
                        .WithMany()
                        .HasForeignKey("SubtitleTVShowID");

                    b.HasOne("Captioneer.API.Entities.Translation", "Translation")
                        .WithMany()
                        .HasForeignKey("TranslationID");

                    b.HasOne("Captioneer.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubtitleMovie");

                    b.Navigation("SubtitleTVShow");

                    b.Navigation("Translation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Captioneer.API.Entities.Translation", b =>
                {
                    b.HasOne("Captioneer.API.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Captioneer.API.Entities.User", b =>
                {
                    b.HasOne("Captioneer.API.Entities.Admin", null)
                        .WithMany("BannedUsers")
                        .HasForeignKey("AdminID");
                });

            modelBuilder.Entity("Captioneer.API.Entities.Admin", b =>
                {
                    b.Navigation("BannedUsers");

                    b.Navigation("RemovedComments");

                    b.Navigation("RemovedMovieSubtitles");

                    b.Navigation("RemovedTVShowSubtitles");
                });
#pragma warning restore 612, 618
        }
    }
}
